#pragma once
#ifndef BEAN_ENV_NATIVE_LAYOUTMANAGER_LAYOUTMANAGERNEWEXECUTOR_H
#define BEAN_ENV_NATIVE_LAYOUTMANAGER_LAYOUTMANAGERNEWEXECUTOR_H
class LayoutManagerNewExecutor {
public:
	LayoutManagerNewExecutor();
	~LayoutManagerNewExecutor();
};
#endif // !BEAN_ENV_NATIVE_LAYOUTMANAGER_LAYOUTMANAGERNEWEXECUTOR_H
